services:
  - type: web
    name: canyoucheat-backend
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: MONGO_URI
        fromDatabase:
          name: canyoucheat-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: AI_SERVICE_URL
        value: https://vivekchaudhary111-canyoucheat-ai.hf.space
      - key: FRONTEND_URL
        value: https://can-you-cheat.vercel.app/

databases:
  - name: canyoucheat-db
    databaseName: canyoucheat
    user: admin